# Generated by Django 3.0 on 2020-01-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_platform', '0002_auto_20200113_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_platform.Post'),
            preserve_default=False,
        ),
    ]
