# Generated by Django 3.0 on 2020-01-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_platform', '0003_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_of', to='discussion_platform.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discussion_platform.Post'),
        ),
    ]
