# Generated by Django 3.0 on 2020-01-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_platform', '0005_auto_20200113_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='discussion_platform.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='discussion_platform.Post'),
        ),
    ]
