# Generated by Django 3.0 on 2020-01-09 04:03

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20200104_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[user_manager.models.User.phone_validator], verbose_name='phone'),
        ),
    ]
