# Generated by Django 3.0 on 2020-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20200109_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='register_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(blank=True, choices=[('s1', 'Semester 1'), ('s2', 'Semester 2'), ('s3', 'Semester 3'), ('s4', 'Semester 4'), ('s5', 'Semester 5'), ('s6', 'Semester 6'), ('s7', 'Semester 7'), ('s8', 'Semester 8')], max_length=2, null=True),
        ),
    ]
