# Generated by Django 3.0 on 2020-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_auto_20200109_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(choices=[('nil', 'No College Selected'), ('kte', 'Rajiv Gandhi Institute of Technology')], default='nill', max_length=5),
        ),
    ]
