# Generated by Django 3.0 on 2020-03-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0008_auto_20200314_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('gradedetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_manager.GradeDetails')),
            ],
            options={
                'verbose_name_plural': 'Report Card',
                'ordering': ['register_no'],
            },
            bases=('user_manager.gradedetails',),
        ),
        migrations.AlterModelOptions(
            name='gradedetails',
            options={'ordering': ['register_no'], 'verbose_name_plural': 'Grade Details'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_manager.ReportCard'),
        ),
    ]
