# Generated by Django 3.0 on 2020-03-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0009_auto_20200314_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gradedetails_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_manager.GradeDetails'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportCard',
        ),
    ]
