# Generated by Django 3.0 on 2020-01-23 15:42

import content_manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes',
            field=models.FileField(default=1, upload_to='notes', validators=[content_manager.models.Module.validate_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content_manager.VideoLecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolecture',
            name='src',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolecture',
            name='thumbnail',
            field=models.ImageField(default='d', upload_to='thumbnail', validators=[content_manager.models.VideoLecture.validate_image]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolecture',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_manager.Topic'),
        ),
    ]
