# Generated by Django 3.0 on 2020-02-06 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('registration_link', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('competition', 'Competition'), ('others', 'Others')], max_length=20)),
                ('clicks', models.ManyToManyField(related_name='clicked_events', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='event_manager.EventTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
