# Generated by Django 3.0 on 2020-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20200206_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
